### ISSUE TITLE
Implement time based theme switcher

### ISSUE THREAD

**Issue by iammatthias** [iammatthias/net#10]
Two color schemes exist for this site, a light and a dark. 
- Light: https://github.com/iammatthias/net/blob/master/src/styles/themeLight.js
- Dark: https://github.com/iammatthias/net/blob/master/src/styles/themeDark.js

Goal: default to _light_ theme. Switch to _dark_ theme programmatically based on local time of day. 
Must work with current theming using Emotion.sh.

**Comment by matthiaskjordan** [comment]
Achieved with `@media (prefers-color-scheme: dark)`, waiting on wider browser support(implemented already, but won't work in most browsers yet).

**Comment by iammatthias** [comment]
Achieved with @media (prefers-color-scheme: dark), waiting on wider browser support(implemented already, but won't work in most browsers yet).
