### ISSUE TITLE
What's the Contentful structure you're referring to?

### ISSUE THREAD

**Issue by jpvalery** [iammatthias/net#18]
> Code can be used as a reference for other Gatsby projects, but this repo will not work out-of-the-box without replicating the Contentful data structure.

Hi Matthias,

Really digging this. I'd love to use it as a basis to redo my portfolio and learn some new skills with Gatsby/Contentful/Netlify. 

Would you be open to share/extrapolate on the Contentful structure you're referring to? 

Thanks in advance for your help!

**Comment by iammatthias** [comment]
You'll need to built a content model in Contentful. 

Here's the GraphQL query from the Index of this repo: https://github.com/iammatthias/net/blob/master/src/pages/index.js

```
export const query = graphql`
  query Index {
    allContentfulExtendedGallery(
      limit: 1000
      sort: { fields: [publishDate], order: DESC }
    ) {
      edges {
        node {
          title
          id
          slug
          publishDate(formatString: "DD MMM YYYY h:mm a")
          heroImage {
            title
            fluid(maxWidth: 1000) {
              ...GatsbyContentfulFluid_withWebp
            }
          }
          body {
            childMarkdownRemark {
              excerpt(pruneLength: 140)
            }
          }
        }
      }
    }
    contentfulHome {
      title
      id
      heroImage {
        title
        fluid(maxWidth: 1000) {
          ...GatsbyContentfulFluid_withWebp
        }
        ogimg: resize(width: 900) {
          src
          width
          height
        }
      }
      body {
        childMarkdownRemark {
          html
        }
      }
    }
  }
`
```

You would need to create content types for `ExtendedGallery` and `Home`, with the respective fields. The Home type is probably the easiest to replicate. 

Home
- Title
- heroImage
  - title
  - src
- body
  - markdown

Best of luck, hope this helps!

**Comment by jpvalery** [comment]
Thanks for the fast reply Matthias.

Just to make sure I got that right, it should look like this?
![image](https://user-images.githubusercontent.com/4112343/51219060-18994080-18fd-11e9-8250-57d8dd1adeaf.png)

Besides the ExtendedGallery and Home, are there any other content models I should create? 
_If you'd rather not disclose this publicly, you could send me that privately_

Thank you so much for your help

**Comment by iammatthias** [comment]
Hey @jpvalery, I don't mind disclosing it. It can all be pieced together from the public GraphQL snippets, after all. 

Content models are as follows: 

#### Home
<img width="725" alt="image" src="https://user-images.githubusercontent.com/5431737/51354884-fffa6900-1a69-11e9-9ad0-1f4568addee4.png">

#### Extended Galleries
<img width="725" alt="image" src="https://user-images.githubusercontent.com/5431737/51354916-1ef8fb00-1a6a-11e9-9a3d-b001ac9edef8.png">

#### Sub Galleries 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/5431737/51354927-2b7d5380-1a6a-11e9-8c86-864436e78c9a.png">

#### Tag
<img width="729" alt="image" src="https://user-images.githubusercontent.com/5431737/51355004-76976680-1a6a-11e9-9068-b6f0bcf6c36c.png">

I think that's all that is explicitly needed to get the galleries working. There are other basic models for the blog and contact page, but they're lifted from [GCN](https://github.com/ryanwiemer/gatsby-starter-gcn).

**Comment by jpvalery** [comment]
Hey @iammatthias ,

Thank you so much for this. I figured most of it but apparently, I overlooked some parts. 

Will let you know once this goes live :) Thanks again!

**Comment by iammatthias** [comment]
Looking forward to it, @jpvalery! Looking forward to seeing what you build.

**Comment by Kowai** [comment]
Hello guys,
I really avoid to ask for help but I don't get this..
I installed gatsby @iammatthias lasted package, changed the contentful IDs, changed the contentful structure of content to fit what's specified in one of the upper comment.

But then when i run "Gastby develop/build" I get the following error :
...
success building schema - 0.205 s
⠋ createPages
error UNHANDLED REJECTION


  TypeError: Cannot read property 'allContentfulPost' of undefined

  - gatsby-node.js:18 graphql.then.result
    C:/Users/Nicolas BURGI/today/gatsby-node.js:18:19

I don't understand what to do.. I thought that maybe it's because there wasn't any data in contentful so I created some, but no changes. Did I forget something? What am I doing wrong ?

I would really apreciate some help.

**Comment by iammatthias** [comment]
This repo is not intended to be a starter—it is the codebase for my personal site. It is left public to serve as an educational resource. Feel free to take a look at how things work, so you can build your own, but support is no longer provided. 

 If you would like to quickly bootstrap a Gatsby + Contentful + Netlify project, I recommend the fantastic [GCN](https://github.com/ryanwiemer/gatsby-starter-gcn) starter. It has an MIT license, unlike this project.
