### ISSUE TITLE
On Windows, graphql doesn't pass query #30

### ISSUE THREAD

**Issue by jeanlucaslima** [iammatthias/net#9]
Just cloned the repo, ran `npm install`, and then `gatsby develop` and it is stuck on this step for 15 minutes now:

![image](https://user-images.githubusercontent.com/1311402/45496491-f5426700-b74b-11e8-974c-9b83ebb2b941.png)

**Comment by iammatthias** [comment]
You need a data structure in Contentful.

This site is based on this starter: https://github.com/ryanwiemer/gatsby-starter-gcn

It's a good place to start for bootstrapping a Gatsby + Contentful site.
